# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - basic/101-aks/*

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    jobs: 
      - job: build
        steps: 
        - script: echo Hello, world!
          displayName: 'Run a one-line script'
          
  - stage: deploy
    jobs:
    - job: deploy
      displayName: Deploy Infra
      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Gitte Vermeiren Azure Internal Consumption(1)(49e23c68-dee0-4c5b-8c21-74acea0a2662)'
          subscriptionId: '49e23c68-dee0-4c5b-8c21-74acea0a2662'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'demo-aks-101'
          location: 'West Europe'
          templateLocation: 'Linked artifact'
          csmFile: '$(System.DefaultWorkingDirectory)/**/101-aks/aks-template.json'
          overrideParameters: '-clusterName "aks101" -dnsPrefix "aks101" -appInsightsLocation "West Europe" -clusterLocation "West Europe" -servicePrincipalClientId "$(ServicePrincipalId)" -servicePrincipalClientSecret "$(ServicePrincipalKey)" -agentCount 3 -agentVMSize Standard_DS2_v2 -kubernetesVersion 1.14.7 -omsLocation "West Europe" -omsWorkspaceName "aks101b60f" -httpApplicationRoutingEnabled false'
          deploymentMode: 'Incremental'
          deploymentName: 'aksbasic_$(Build.BuildId)'
          deploymentOutputs: 'deploymentOutputs'