# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: build
    jobs: 
      - job: build
        steps: 
        - script: echo Hello, world!
          displayName: 'Run a one-line script'
          
  - stage: deploy
    jobs:
    - job: deploy
      displayName: Deploy Infra
      steps:
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Gitte Vermeiren Azure Internal Consumption(1)(49e23c68-dee0-4c5b-8c21-74acea0a2662)'
          subscriptionId: '49e23c68-dee0-4c5b-8c21-74acea0a2662'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'demo-aks-network'
          location: 'West Europe'
          templateLocation: 'Linked artifact'
          csmFile: '$(System.DefaultWorkingDirectory)/**/101-advanced-networking/network-template.json'
          deploymentMode: 'Incremental'
          deploymentName: '$(Build.BuildId)'
          deploymentOutputs: 'deploymentOutputs'
      
      - task: AzureResourceManagerTemplateDeployment@3
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'Gitte Vermeiren Azure Internal Consumption(1)(49e23c68-dee0-4c5b-8c21-74acea0a2662)'
          subscriptionId: '49e23c68-dee0-4c5b-8c21-74acea0a2662'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'demo-aks-network'
          location: 'West Europe'
          templateLocation: 'Linked artifact'
          csmFile: '$(System.DefaultWorkingDirectory)/**/101-advanced-networking/aks-template.json'
          overrideParameters: '-resourceName "aksnw" -dnsPrefix "aksnw" -location "West Europe" -existingServicePrincipalObjectId "$(ServicePrincipalObjectId)" -existingServicePrincipalClientId "$(ServicePrincipalId)" -existingServicePrincipalClientSecret "$(ServicePrincipalKey)" -kubernetesVersion 1.14.7 -enableHttpApplicationRouting false -existingVirtualNetworkName "VNet1" -existingVirtualNetworkResourceGroup 'demo-aks-network' -existingSubnetName "Subnet1"'
          deploymentMode: 'Incremental'
          deploymentName: '$(Build.BuildId)'
          deploymentOutputs: 'deploymentOutputs'